# Generated by Django 6.0.5 on 2026-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
