# Generated by Django 6.0.5 on 2026-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
