# Generated by Django 6.0.5 on 2026-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_customuser_image_course_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
